version: '2'
services:
  postgreskong:
    image: postgres:9.4
    ports:
     - 5432
    environment:
     - POSTGRES_USER=kong
     - POSTGRES_DB=kong
  kong:
    image: localz/kong:develop-1.2.13
    container_name: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgreskong
      - KONG_PG_USER=kong
    ports:
      - "8000:8000"
      - "8443"
      - "8001:8001"
      - "7946"
      - "7946/udp"
    links:
      - postgreskong