# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Run vet & lint
      run: |
        go vet ./...

    - name: Lint Code Base
      uses: github/super-linter@v4.9.2
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LINTER_RULES_PATH: '.'
        MARKDOWN_CONFIG_FILE: .markdownlint.yml
        VALIDATE_MARKDOWN: true
        VALIDATE_BASH: true

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Test
      run: go test -v ./...
      
    -
      name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2.5.0
      with:
        version: latest
        args: release --rm-dist
      env:
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
        # GitHub sets this automatically
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
